### ISSUE TITLE
Consider using System.IO.Abstractions

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitTools.Core#24]

**Comment by dazinator** [comment]
If we only need read file access, could also consider `Microsoft.Extensions.FileProviders` as this is netstandard compatible. The idea is you depend on the `IFileProvider` abstraction to get read access to files, and that this can be backed by various implementations such as a `PhysicalFileProvider` or I created an InMemoryFileProvider for unit testing purposes: https://www.nuget.org/packages/Dazinator.AspNet.Extensions.FileProviders/1.4.0-unstable0001

**Comment by asbjornu** [comment]
As GitVersion stopped using `GitTools.Core` in GitTools/GitVersion#1581, this issue is unfortunately not relevant anymore and the whole repository will be archived. Please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and see if it solves whatever problem you had when you submitted this issue. If the problem persists, please submit a new issue or PR against the [GitVersion repository](https://github.com/GitTools/GitVersion/).
