### ISSUE TITLE
LibGitExtensions.IsDetachedHead is redundant

### ISSUE THREAD

**Issue by maximpashuk** [GitTools/GitTools.Core#30]
https://github.com/GitTools/GitTools.Core/blob/244cca386321d6f8c90cf31cd3c4734c8932b4da/src/GitTools.Core/GitTools.Core.Shared/Git/Extensions/LibGitExtensions.cs#L93

Instead of this you always can use **Repository.Info.IsHeadDetached** from libgit2sharp.

**Comment by asbjornu** [comment]
As GitVersion stopped using `GitTools.Core` in GitTools/GitVersion#1581, this issue is unfortunately not relevant anymore and the whole repository will be archived. Please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and see if it solves whatever problem you had when you submitted this issue. If the problem persists, please submit a new issue or PR against the [GitVersion repository](https://github.com/GitTools/GitVersion/).
