### ISSUE TITLE
Remote repo - bare cloning and fetching.

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitTools.Core#4]
For remote repo support, my limited understanding through looking at the code in the multiple tools is that we: 
1. Do a `bare` clone (assuming this is for speed / bandwidth / file system gains over full clone)
2. Do some prep / configuration of that bare clone, so that we can begin using it locally, enough to check files out from a branches etc.

Any chance we can get this process documented - especially around the additional configuration that's made to the bare clone of the repo and why its necessary? (I'd like to understand it) 

Also, it works on the assumption that we delete any existing repo, and do a fresh bare clone every time - to ensure latest, but i've noticed for GitVersion we are also trying to make an improvement to not delete / do a fresh bare clone every time - but instead keep the existing one up to date. https://github.com/ParticularLabs/GitVersion/pull/399#discussion-diff-26903087

It would be nice to be able to point users at some wiki saying "see - this is exactly what we do to the repo after its cloned, and why" - things like checking for remotes , fetching etc etc.. I'd also like to point myself at that page..

Let's then also get that documented functionality into the core (when it all works)

**Comment by asbjornu** [comment]
As GitVersion stopped using `GitTools.Core` in GitTools/GitVersion#1581, this issue is unfortunately not relevant anymore and the whole repository will be archived. Please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and see if it solves whatever problem you had when you submitted this issue. If the problem persists, please submit a new issue or PR against the [GitVersion repository](https://github.com/GitTools/GitVersion/).
