### ISSUE TITLE
Dependcies look wrong on nuget

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitTools.Core#46]
As of the latest PR to support `netstandard`, I think the dependencies listed for `net45` look a bit wrong:
https://www.nuget.org/packages/GitTools.Core/

I think it will work with net45 still but its pulling in the netstandard packages when I think it should just be referencing the bcl assemblies similar to net4.0.

Might need to fix that..

**Comment by asbjornu** [comment]
As GitVersion stopped using `GitTools.Core` in GitTools/GitVersion#1581, this issue is unfortunately not relevant anymore and the whole repository will be archived. Please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and see if it solves whatever problem you had when you submitted this issue. If the problem persists, please submit a new issue or PR against the [GitVersion repository](https://github.com/GitTools/GitVersion/).
