### ISSUE TITLE
Create init method on all tools to help the user create a config

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitTools.Core#6]

**Comment by GeertvanHorrik** [comment]
GitVersion is done. Maybe we can move the initialization wizard code into GitTools.Core once we want to apply it to all products.

**Comment by asbjornu** [comment]
As GitVersion stopped using `GitTools.Core` in GitTools/GitVersion#1581, this issue is unfortunately not relevant anymore and the whole repository will be archived. Please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and see if it solves whatever problem you had when you submitted this issue. If the problem persists, please submit a new issue or PR against the [GitVersion repository](https://github.com/GitTools/GitVersion/).
