### ISSUE TITLE
Create a centralized command line (same as GitToolsConfig.yml)

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitTools.Core#9]
Discuss what should be in the core so it is shared among all projects.

**Comment by asbjornu** [comment]
As GitVersion stopped using `GitTools.Core` in GitTools/GitVersion#1581, this issue is unfortunately not relevant anymore and the whole repository will be archived. Please try [the latest build of GitVersion](https://www.nuget.org/packages/GitVersionCore/5.0.0-beta4-1) and see if it solves whatever problem you had when you submitted this issue. If the problem persists, please submit a new issue or PR against the [GitVersion repository](https://github.com/GitTools/GitVersion/).
